sudo: required
language: minimal
services:
    - docker
script:
    - docker build . -t arch
    - docker run  -v $(pwd):/home/docker/build arch -c "cd /tmp;
      git clone --depth=1 /home/docker/build;
      cd build/pkg;
      makepkg -s --noconfirm;
      sudo mv *.pkg.tar.* /home/docker/build"
deploy:
    provider: releases
    api_key:
        secure: "GQItTPaB2FmYZvKQNUz+GOhNE4bJRz0NgOAEe3vKwnJ8q8CYITlv2cPUAXbMWgeO/KVf71/9hUXGRpAAjn2KRBkGck8jhVpTrBEwl/Qt7pMfOHBhJ0kgp+6wiFtH7NN9PHYxqiIqAQLE4oQ10AhULLjmWwyb12GAWnUGN9laoxwDBe7E4nzOhXhRW5T5hRQhGxwR1xBEgxv27/I5v48RmOviV4pjlXo86OGwmiMTvbotWmIfUnKTRjsgBfwq2hozRQo4GGLaSaakt9etNa3yPWhDTh6ZluO+cvy1mC/n4YgSCeHOnm6biYaAY4RZD+v/28J1lPbHzXJ5Y5cdzS3yBr0yqH62wNvHcCeUOdTMFwy/5Ke3FBFOHBLnKdoj2CYaKgIwE5DcCdvqjKHT4ZYhw+d1DeOU8Uj3cH6A3iIzQrIlpWAuac0l4I1NKUFAqzDaILc5AyFIXERlHHCSstTsA2Fo5AAiAPFpmGVQ1J4f5tad9KWk9wCr9BvMgFUEiL6l9N5GmmX6y8pcgwVFQpAdUrv3+rl9kNibH4711eeoNOp7nx70DZmHCm+OvTQSq21oF2AIfeSSm28KxHhCTli/eF95CLOFZf21p+oslh4fjFukyhDpNgk72h2i1tdo6Wx/KJ8U4WBBnbwmWBm3kkqwp61013Eu0qO1ksn19e2Ek+c="
    file_glob: true
    file: "*.pkg.tar.*"
    skip_cleanup: true
    on:
        repo: otreblan/pooii-tarea-2-entrega-21-04-otreblan
        tags: true
