sudo: required
services:
    - docker
script:
    - docker build . -t arch
    - docker run  -v $(pwd):/home/docker/build arch -c "cd /tmp;
      git clone --depth=1 /home/docker/build;
      cd build/pkg;
      makepkg -s --noconfirm;
      sudo mv *.pkg.tar.* /home/docker/build"
deploy:
    provider: releases
    api_key:
    secure: GGYXQM0aYXWi8yvvS6Z9jgnFvrYvIc5do8BKV9Wu+PvbZOiCE2lvw42dDNbsG8FQwh+4Hjdzk92m1YjIeVyX7VCAWpMCETlKFJ3t1bY8hbq2Kx7mnGgqthBGdaM48kasa5dfvjyStXrs59Rzf40+RK/OVzL6j3rro1KRXdrmKLQR+UJBHTydxtXFg3QT1rVA7Bpfs1l0/y1HCVUG0Ysw0A4vFv9W8WG+vGecLxU6ykxSTyfrXg/SVYY6YcEbR9oWrHUav0aTAaAC78ywoPu3gR+axBlaha34vXkImuj6+lT+v1H8PQvtZe+akzMpxCa4J3KWv6LcuiX8S0/C7HOznzRzZnbCM4cWd2Q4oxQkGSD76xw1R9vIN5s5AOcbf35/34C1FCUgwkl2HZXtYXdroIVQTkH+FYYx86L9drk/JY3eKTMNTZV3wjHXp/qb4ovZinMywhPo6IFcIjoxedp7doLI2onHumndr0c8g3V7L0y7L4H/xLSJ2Ye7w6fsevDUS/UUqQraxGTQ56htMGJOcTBTHq5VaCKpwAX2gwgosV4KUogcKamP6Q4xHYpTgkQrlonVHEGodsiZigOngViiy+HSeVIdy7+wKYsBDGhcYvsxxNf4/9KVYbiZciHLdS8L8MQt10rvBpMp0fTWtFaZx9+CMGXAyJbdAkI33e7Y/YA=
    file_glob: true
    file: "*.pkg.tar.*"
    skip_cleanup: true
    on:
        repo: otreblan/pooii-tarea-2-entrega-21-04-otreblan
        tags: true
